### ISSUE TITLE
Package into AUR

### ISSUE THREAD

**Issue by Kyle-Thompson** [sector-f/admiral#6]
Is there any plan to package this into the AUR or something equivalent so it won't be required to build from source every time?

**Comment by sector-f** [comment]
There is an [admiral-git](https://aur.archlinux.org/packages/admiral-git/) AUR package, although I'm not the one who maintains it.

(With that said, installing things from the AUR often does involve building them from source; it's just that the process is mostly automated).

**Comment by Kyle-Thompson** [comment]
I see. Well for now pulling from github and manually compiling isn't a big deal.
